### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by zeddo123** [squirrel-writer/squirrel#10]
Adding very simple github actions to run unittest on commits and pull requests will go along way in helping the project be more stable.

**Comment by RishiKumarRay** [comment]
I would like to do this

**Comment by zeddo123** [comment]
@RishiKumarRay thank you for the interest. You can open a PR.

**Comment by RishiKumarRay** [comment]
I have tried setting up, i think you have to fix pytest errors and then it will work fine
![Uploading Screenshot from 2022-02-02 16-27-22.png…]()

**Comment by RishiKumarRay** [comment]
![Uploading Screenshot from 2022-02-02 16-27-22.png…]()

**Comment by RishiKumarRay** [comment]
![Screenshot from 2022-02-02 16-37-52](https://user-images.githubusercontent.com/87641376/152142604-a516f883-a162-4ed9-bf70-133ec8272ef5.png)

**Comment by zeddo123** [comment]
That's probably an error due to `pipenv` not being activated. You should use `tox`(the dependencies will get installed) so that it tests on multiple versions of python.

**Comment by RishiKumarRay** [comment]
@zeddo123 please review the PR , is this how you wanted the action?
