### ISSUE TITLE
Support for python3.8

### ISSUE THREAD

**Issue by zeddo123** [squirrel-writer/squirrel#12]
After some issue I had with tox and multiple versions of pythons, it turns out `squirrel` is not compatible with `python3.8` due to:

```Python
AttributeError: module 'xml.etree.ElementTree' has no attribute 'indent'
```
I will be dropping support of python3.8 until we find a replacement for `indent`.

**Comment by zeddo123** [comment]
I'm reopening this until the `indent` function implemented by @Bchass in PR #15 is fixed.

**Comment by Bchass** [comment]
I'll take a look at this upcoming week

**Comment by Bchass** [comment]
@zeddo123 Do you have a Discord or a Twitter I could directly DM you with some questions regarding the project? I have the indent function working correctly on my end now, but I just want to confirm a few things before I push a commit again.

**Comment by zeddo123** [comment]
I have a discord account but I'll have to find it (don't use it that much). Alternatively, you can mark the PR as a draft. Last time I only glanced at the function without giving it much thought.
