### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by TzviGreenfeld** [squirrel-writer/squirrel#17]
I think you've got a typo in [overview.py](https://github.com/squirrel-writer/squirrel/blob/35c7823b3f0472367056c490b3463105c61bdc44/squirrel/commands/overview.py)
in line 44:
https://github.com/squirrel-writer/squirrel/blob/35c7823b3f0472367056c490b3463105c61bdc44/squirrel/commands/overview.py#L44
probably should be "Due Date" insted of "Due Data".
saw it in [this](https://github.com/squirrel-writer/squirrel/raw/master/squirrel-overview-output.png) image, in the README.md file

**Comment by zeddo123** [comment]
Thank you for reporting!
