### ISSUE TITLE
Add ability to specify or ignore any files project level

### ISSUE THREAD

**Issue by zeddo123** [squirrel-writer/squirrel#6]
Simply put this would allow users to either specify files they want counted or some files they want them ignored.

**Comment by h-leth** [comment]
> Do you think it's important to specify the file type in the project level and not in the plugins? wouldn't it be better to have the ability to exclude file like a .gitignore?

Is it enough to load the `.squrrel_ignore` at startup of watch or do we want it to be monitored and update while the daemon is running?

Here are my toughts so far:
- Loads file at startup
- Sort extensions, filename and directorys to seperate `list`
- Implement the lists into the daemon and have it look for patterns to ignore

**Comment by zeddo123** [comment]
>do we want it to be monitored and update while the daemon is running?

Hmm. I don't think it's necessary to have the file monitored. It's most likely going to be set one time.
